model:
  model_path: /private/wy/pretrained_models/Qwen2.5-Omni-7B
  quant_method: morpho
  apply_hooks: false
  save_attention_maps: false
  save_per_head_attention: false
quant:
  simulate_hif8: false
  activation_bitwidth: 4
  keep_special_layer: false
  debug_quant_act: false
  gamma_inf: 0.5
  gamma_cos: 0.75
  calib_size: 128
  batch_size: 4
data:
  only_samples_with_images: false
  num_samples: -1
  target_subject: all
  dataset_dir: /private/wy/datasets
  run_pca: false
run:
  save_dir: /private/wy/logs/MorphoQuant/mmmu_results
  seed: 2025
