model:
  model_path: /private/wy/pretrained_models/Qwen2.5-Omni-7B
  quant_method: bf16
  apply_hooks: false
  save_attention_maps: false
  save_per_head_attention: false
quant:
  simulate_hif8: false
  simulate_hif4: false
  simulate_smoothquant: false
  activation_bitwidth: 16
  keep_special_layer: false
  debug_quant_act: false
  calib_size: 64
  batch_size: 1
data:
  only_samples_with_images: false
  num_samples: -1
  data_root: /private/wy/datasets/air-bench/Foundation
  output_file: /private/wy/logs/MorphoQuant/airbench/Foundation_result_qwen2.5_omni_7b_fp16.jsonl
  run_pca: false
run:
  save_dir: /private/wy/logs/MorphoQuant/airbench_results
  seed: 2025
