model:
  model_path: /private/wy/pretrained_models/Qwen2.5-Omni-3B
  quant_method: qlora
  apply_hooks: false
  save_attention_maps: false
  save_per_head_attention: false
quant:
  qlora_quant_type: nf4
  qlora_double_quant: true
  qlora_compute_dtype: bfloat16
  activation_bitwidth: 16
  calib_size: 64
  search_size: 16
  batch_size: 8
data:
  only_samples_with_images: false
  num_samples: -1
run:
  save_dir: /private/wy/logs/MorphoQuant/scienceqa_qlora_results
  seed: 2025
