model:
  model_path: /private/wy/pretrained_models/Qwen2.5-Omni-3B
  quant_method: bf16
  apply_hooks: false
  save_attention_maps: false
  save_per_head_attention: false
quant:
  simulate_hif8: true
  activation_bitwidth: 8
  keep_special_layer: false
  debug_quant_act: false
  gamma_inf: 0.5
  gamma_cos: 1.0
  calib_size: 128
  search_size: 16
  batch_size: 8
data:
  only_samples_with_images: false
  num_samples: -1
  data_root: /private/wy/datasets/air-bench/Foundation
  output_file: /private/wy/logs/MorphoQuant/airbench/Foundation_result_qwen2.5_omni_hif8.jsonl
  run_pca: false
run:
  save_dir: /private/wy/pretrained_models/qwen2.5-omni-3b-hif8-calibrated
  seed: 2025
