model:
  model_path: /private/wy/pretrained_models/InternVL2_5-8B
  model_type: internvl2_5
  quant_method: qlora
  apply_hooks: false
  save_attention_maps: false
  save_per_head_attention: false
quant:
  qlora_quant_type: nf4
  qlora_double_quant: true
  qlora_compute_dtype: bfloat16
  activation_bitwidth: 16
  calib_size: 128
  search_size: 16
  batch_size: 8
data:
  only_samples_with_images: false
  num_samples: -1
  data_root: /private/wy/datasets/air-bench/Foundation
  output_file: /private/wy/logs/MorphoQuant/airbench/Foundation_result_internvl2.5_qlora_w4a16.jsonl
  run_pca: false
  internvl_max_num_tiles: 8
  internvl_calib_max_num_tiles: 6
  internvl_calib_max_images: 2
  internvl_eval_max_images: 2
  internvl_eval_max_num_tiles: 6
run:
  save_dir: /private/wy/logs/MorphoQuant/airbench_internvl25_qlora_results
  seed: 2025
