model:
  model_path: /private/wy/pretrained_models/Qwen2.5-Omni-3B
  quant_method: morpho
  apply_hooks: false
  save_attention_maps: false
  save_per_head_attention: false
quant:
  simulate_hif8: false
  activation_bitwidth: 4
  keep_special_layer: false
  debug_quant_act: false
  gamma_inf: 0.5
  gamma_cos: 1.0
  calib_size: 128
  batch_size: 4
  calib_without_video: true
data:
  only_samples_with_images: false
  num_samples: -1
