model:
  model_path: /private/wy/pretrained_models/Qwen2.5-Omni-7B
  quant_method: bf16
  apply_hooks: false
  save_attention_maps: false
  save_per_head_attention: false
quant:
  simulate_hif8: false
  simulate_hif4: false
  simulate_smoothquant: false
  simulate_awq: false
  simulate_mbq: true
  mbq_weight_bits: 4
  mbq_act_bits: 4
  mbq_group_size: 128
  mbq_n_grid: 20
  mbq_modalities: [text, multimodal]
  activation_bitwidth: 16
  keep_special_layer: false
  debug_quant_act: false
  gamma_inf: 0.5
  gamma_cos: 1.0
  lp_norm: 3.0
  use_cosine_loss: false
  sparse_buffer_ratio: 1.5
  search_ratio_lower_bound: 0.6
  calib_size: 64
  search_size: 16
  batch_size: 8
  outlier_std_threshold: 2.0
data:
  only_samples_with_images: false
  num_samples: -1
  data_root: /private/wy/datasets/air-bench/Foundation
  output_file: /private/wy/logs/MorphoQuant/airbench/Foundation_result_qwen2.5_omni_7b_mbq_w4a4.jsonl
  run_pca: false
run:
  save_dir: /private/wy/logs/MorphoQuant/airbench_results
  seed: 2025
